### ISSUE TITLE
WIN : manifest.json file never copied to 4D plugin bundle

### ISSUE THREAD

**Issue by xyloweb** [miyako/4d-plugin-rename#1]
Hi miyako,

The manifest.json file must be copied to 4D plugin bundle at the end of compilation.
I suppose it was the case under mac os plateform with an Xcode instruction but under Visual Studio this copy is missing.

You can do that with a post-build command like this 
`xcopy /Y "$(ProjectDir)manifest.json" "$(ProjectDir)test\plugins\$(ProjectName).bundle\contents\"`

**Comment by miyako** [comment]
Thank you for flagging the issue. 

Unlike Xcode which knows how to build a bundle, the VC project contains basic instructions to generate a DLL with the file extension 4DX. The manifest, as well as Resources, Info.plist, etc are typically copied to their respective directories when the project is generated,  not when the plugin is built. But your way is more comprehensive, especially when the manifest is updated. In my work I build on Windows, then build on Mac for notarisation, so I admit, I was lazy and did not care to update resources after each build.
